import type { CodegenConfig } from '@graphql-codegen/cli'

import { BACKEND_GraphQL_BASE_URL } from './src/shared/config'

const config: CodegenConfig = {
  documents: ['src/**/*.{graphql,gql,ts}'],
  config: {
    content: '/** THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */',
  },
  generates: {
    'src/': {
      config: {
        withHooks: true,
      },
      plugins: ['typescript-operations', 'typescript-react-apollo', 'add'],
      preset: 'near-operation-file',
      presetConfig: {
        baseTypesPath: 'shared/api/models.gen.ts',
        extension: '.generated.ts',
      },
    },
    'src/shared/api/models.gen.ts': { plugins: ['typescript', 'add'] },
  },
  ignoreNoDocuments: true, // for better experience with the watcher
  schema: BACKEND_GraphQL_BASE_URL,
  overwrite: true,
}

export default config
