/** THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as Types from '../../../../shared/api/models.gen';

import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions = {} as const;
export type Ban_UserMutationVariables = Types.Exact<{
  userId: Types.Scalars['Int']['input'];
  banReason: Types.Scalars['String']['input'];
}>;


export type Ban_UserMutation = { __typename?: 'Mutation', banUser: boolean };


export const Ban_UserDocument = gql`
    mutation BAN_USER($userId: Int!, $banReason: String!) {
  banUser(userId: $userId, banReason: $banReason)
}
    `;
export type Ban_UserMutationFn = Apollo.MutationFunction<Ban_UserMutation, Ban_UserMutationVariables>;

/**
 * __useBan_UserMutation__
 *
 * To run a mutation, you first call `useBan_UserMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useBan_UserMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [banUserMutation, { data, loading, error }] = useBan_UserMutation({
 *   variables: {
 *      userId: // value for 'userId'
 *      banReason: // value for 'banReason'
 *   },
 * });
 */
export function useBan_UserMutation(baseOptions?: Apollo.MutationHookOptions<Ban_UserMutation, Ban_UserMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<Ban_UserMutation, Ban_UserMutationVariables>(Ban_UserDocument, options);
      }
export type Ban_UserMutationHookResult = ReturnType<typeof useBan_UserMutation>;
export type Ban_UserMutationResult = Apollo.MutationResult<Ban_UserMutation>;
export type Ban_UserMutationOptions = Apollo.BaseMutationOptions<Ban_UserMutation, Ban_UserMutationVariables>;