/** THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as Types from '../../../../shared/api/models.gen';

import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions = {} as const;
export type Un_Ban_UserMutationVariables = Types.Exact<{
  userId: Types.Scalars['Int']['input'];
}>;


export type Un_Ban_UserMutation = { __typename?: 'Mutation', unbanUser: boolean };


export const Un_Ban_UserDocument = gql`
    mutation UN_BAN_USER($userId: Int!) {
  unbanUser(userId: $userId)
}
    `;
export type Un_Ban_UserMutationFn = Apollo.MutationFunction<Un_Ban_UserMutation, Un_Ban_UserMutationVariables>;

/**
 * __useUn_Ban_UserMutation__
 *
 * To run a mutation, you first call `useUn_Ban_UserMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUn_Ban_UserMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [unBanUserMutation, { data, loading, error }] = useUn_Ban_UserMutation({
 *   variables: {
 *      userId: // value for 'userId'
 *   },
 * });
 */
export function useUn_Ban_UserMutation(baseOptions?: Apollo.MutationHookOptions<Un_Ban_UserMutation, Un_Ban_UserMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<Un_Ban_UserMutation, Un_Ban_UserMutationVariables>(Un_Ban_UserDocument, options);
      }
export type Un_Ban_UserMutationHookResult = ReturnType<typeof useUn_Ban_UserMutation>;
export type Un_Ban_UserMutationResult = Apollo.MutationResult<Un_Ban_UserMutation>;
export type Un_Ban_UserMutationOptions = Apollo.BaseMutationOptions<Un_Ban_UserMutation, Un_Ban_UserMutationVariables>;