query GET_FOLLOWERS($pageNumber: Int = 1, $pageSize: Int = 10, $sortBy: String = "createdAt", $sortDirection: SortDirection = desc, $userId: Int! ){
    getFollowers(pageNumber: $pageNumber, pageSize: $pageSize, sortBy: $sortBy, sortDirection: $sortDirection, userId: $userId) {
        items {
            userId
            createdAt
            id
            userName
        }
        page
        pageSize
        pagesCount
        totalCount
    }
}