/** THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as Types from '../../../../shared/api/models.gen';

import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions = {} as const;
export type Get_FollowersQueryVariables = Types.Exact<{
  pageNumber?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  pageSize?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  sortBy?: Types.InputMaybe<Types.Scalars['String']['input']>;
  sortDirection?: Types.InputMaybe<Types.SortDirection>;
  userId: Types.Scalars['Int']['input'];
}>;


export type Get_FollowersQuery = { __typename?: 'Query', getFollowers: { __typename?: 'FollowPaginationModel', page: number, pageSize: number, pagesCount: number, totalCount: number, items: Array<{ __typename?: 'Follow', userId: number, createdAt: any, id: number, userName?: string | null }> } };


export const Get_FollowersDocument = gql`
    query GET_FOLLOWERS($pageNumber: Int! = 1, $pageSize: Int! = 10, $sortBy: String = "createdAt", $sortDirection: SortDirection = desc, $userId: Int!) {
  getFollowers(
    pageNumber: $pageNumber
    pageSize: $pageSize
    sortBy: $sortBy
    sortDirection: $sortDirection
    userId: $userId
  ) {
    items {
      userId
      createdAt
      id
      userName
    }
    page
    pageSize
    pagesCount
    totalCount
  }
}
    `;

/**
 * __useGet_FollowersQuery__
 *
 * To run a query within a React component, call `useGet_FollowersQuery` and pass it any options that fit your needs.
 * When your component renders, `useGet_FollowersQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGet_FollowersQuery({
 *   variables: {
 *      pageNumber: // value for 'pageNumber'
 *      pageSize: // value for 'pageSize'
 *      sortBy: // value for 'sortBy'
 *      sortDirection: // value for 'sortDirection'
 *      userId: // value for 'userId'
 *   },
 * });
 */
export function useGet_FollowersQuery(baseOptions: Apollo.QueryHookOptions<Get_FollowersQuery, Get_FollowersQueryVariables> & ({ variables: Get_FollowersQueryVariables; skip?: boolean; } | { skip: boolean; }) ) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<Get_FollowersQuery, Get_FollowersQueryVariables>(Get_FollowersDocument, options);
      }
export function useGet_FollowersLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<Get_FollowersQuery, Get_FollowersQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<Get_FollowersQuery, Get_FollowersQueryVariables>(Get_FollowersDocument, options);
        }
export function useGet_FollowersSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<Get_FollowersQuery, Get_FollowersQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<Get_FollowersQuery, Get_FollowersQueryVariables>(Get_FollowersDocument, options);
        }
export type Get_FollowersQueryHookResult = ReturnType<typeof useGet_FollowersQuery>;
export type Get_FollowersLazyQueryHookResult = ReturnType<typeof useGet_FollowersLazyQuery>;
export type Get_FollowersSuspenseQueryHookResult = ReturnType<typeof useGet_FollowersSuspenseQuery>;
export type Get_FollowersQueryResult = Apollo.QueryResult<Get_FollowersQuery, Get_FollowersQueryVariables>;