query GET_USER_POSTS($userId: Int!, $endCursorId: Int) {
  getPostsByUser(userId: $userId, endCursorId: $endCursorId) {
    pageSize
    totalCount
    pagesCount
    items {
      id
      url
      createdAt
    }
  }
}