/** THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as Types from '../../../shared/api/models.gen';

import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions = {} as const;
export type OnNewPostSubscriptionVariables = Types.Exact<{ [key: string]: never; }>;


export type OnNewPostSubscription = { __typename?: 'Subscription', postAdded: { __typename?: 'Post', id: number, ownerId: number, description: string, createdAt: any, updatedAt: any, images?: Array<{ __typename?: 'ImagePost', id?: number | null, createdAt?: any | null, url?: string | null }> | null, postOwner: { __typename?: 'PostOwnerModel', id: number, userName: string, firstName?: string | null, lastName?: string | null, avatars?: Array<{ __typename?: 'Avatar', url?: string | null }> | null }, userBan?: { __typename?: 'UserBan', reason: string, createdAt: any } | null } };


export const OnNewPostDocument = gql`
    subscription OnNewPost {
  postAdded {
    images {
      id
      createdAt
      url
    }
    id
    ownerId
    description
    createdAt
    updatedAt
    postOwner {
      id
      userName
      firstName
      lastName
      avatars {
        url
      }
    }
    userBan {
      reason
      createdAt
    }
  }
}
    `;

/**
 * __useOnNewPostSubscription__
 *
 * To run a query within a React component, call `useOnNewPostSubscription` and pass it any options that fit your needs.
 * When your component renders, `useOnNewPostSubscription` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the subscription, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useOnNewPostSubscription({
 *   variables: {
 *   },
 * });
 */
export function useOnNewPostSubscription(baseOptions?: Apollo.SubscriptionHookOptions<OnNewPostSubscription, OnNewPostSubscriptionVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useSubscription<OnNewPostSubscription, OnNewPostSubscriptionVariables>(OnNewPostDocument, options);
      }
export type OnNewPostSubscriptionHookResult = ReturnType<typeof useOnNewPostSubscription>;
export type OnNewPostSubscriptionResult = Apollo.SubscriptionResult<OnNewPostSubscription>;