/** THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as Types from '../../../shared/api/models.gen';

import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions = {} as const;
export type GetPostsListsQueryVariables = Types.Exact<{
  endCursorPostId?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  searchTerm?: Types.InputMaybe<Types.Scalars['String']['input']>;
  pageSize?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  sortBy?: Types.InputMaybe<Types.Scalars['String']['input']>;
  sortDirection?: Types.InputMaybe<Types.SortDirection>;
}>;


export type GetPostsListsQuery = { __typename?: 'Query', getPosts: { __typename?: 'PostsPaginationModel', pageSize: number, pagesCount: number, totalCount: number, items: Array<{ __typename?: 'Post', id: number, ownerId: number, description: string, createdAt: any, updatedAt: any, images?: Array<{ __typename?: 'ImagePost', id?: number | null, createdAt?: any | null, url?: string | null, width?: number | null, height?: number | null, fileSize?: number | null }> | null, postOwner: { __typename?: 'PostOwnerModel', id: number, userName: string, firstName?: string | null, lastName?: string | null, avatars?: Array<{ __typename?: 'Avatar', url?: string | null, width?: number | null, height?: number | null, fileSize?: number | null }> | null }, userBan?: { __typename?: 'UserBan', reason: string, createdAt: any } | null }> } };


export const GetPostsListsDocument = gql`
    query GetPostsLists($endCursorPostId: Int, $searchTerm: String, $pageSize: Int = 10, $sortBy: String = "createdAt", $sortDirection: SortDirection = desc) {
  getPosts(
    pageSize: $pageSize
    sortBy: $sortBy
    sortDirection: $sortDirection
    searchTerm: $searchTerm
    endCursorPostId: $endCursorPostId
  ) {
    pageSize
    pagesCount
    totalCount
    items {
      images {
        id
        createdAt
        url
        width
        height
        fileSize
      }
      id
      ownerId
      description
      createdAt
      updatedAt
      postOwner {
        id
        userName
        firstName
        lastName
        avatars {
          url
          width
          height
          fileSize
        }
      }
      userBan {
        reason
        createdAt
      }
    }
  }
}
    `;

/**
 * __useGetPostsListsQuery__
 *
 * To run a query within a React component, call `useGetPostsListsQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetPostsListsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetPostsListsQuery({
 *   variables: {
 *      endCursorPostId: // value for 'endCursorPostId'
 *      searchTerm: // value for 'searchTerm'
 *      pageSize: // value for 'pageSize'
 *      sortBy: // value for 'sortBy'
 *      sortDirection: // value for 'sortDirection'
 *   },
 * });
 */
export function useGetPostsListsQuery(baseOptions?: Apollo.QueryHookOptions<GetPostsListsQuery, GetPostsListsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<GetPostsListsQuery, GetPostsListsQueryVariables>(GetPostsListsDocument, options);
      }
export function useGetPostsListsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<GetPostsListsQuery, GetPostsListsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<GetPostsListsQuery, GetPostsListsQueryVariables>(GetPostsListsDocument, options);
        }
export function useGetPostsListsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<GetPostsListsQuery, GetPostsListsQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<GetPostsListsQuery, GetPostsListsQueryVariables>(GetPostsListsDocument, options);
        }
export type GetPostsListsQueryHookResult = ReturnType<typeof useGetPostsListsQuery>;
export type GetPostsListsLazyQueryHookResult = ReturnType<typeof useGetPostsListsLazyQuery>;
export type GetPostsListsSuspenseQueryHookResult = ReturnType<typeof useGetPostsListsSuspenseQuery>;
export type GetPostsListsQueryResult = Apollo.QueryResult<GetPostsListsQuery, GetPostsListsQueryVariables>;